sculpin_content_types:
    posts:
        permalink: article/:slug_title/

sculpin:
    permalink: pretty
# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
#sculpin_content_types:
#    posts:
#        enabled: false
